server.port: 7105
debug: false

props:
  app-version: 1.0.0.OPENWEATHER
  openweather-api:
    app-id: 8d9c1c7055ec41a33a12e19d3921dfce
    service-schema: http
    host-uri: api.openweathermap.org
    weather-context: /data/2.5/weather
  authentication:
    user:
      username: claudiu
      password: pass123
    admin:
      username: admin
      password: admin123

resttemplate.conn.timeout: 15000
resttemplate.read.timeout: 15000

spring:
  security:
    oauth2:
      client:
        registration:
          openweather-api-client:
            provider: openweather-api-provider
            client-id: openweather-api
            client-secret: "{noop}openweather-secret"
            authorization-grant-type: "client_credentials"
            scope: "read,write"
        provider:
          openweather-api-provider:
            issuer-uri: http://localhost:8090
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    name: openweather
    url: jdbc:h2:~/openweather

logging.level:
  root: INFO
